jwt:
    signing-key: 3549a63e-0736-4511-8bf9-ef2de1d9fc9a
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
zap:
    level: info
    prefix: '[ygpt/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1
redis:
    name: ""
    addr: 10.10.1.200:16371
    password: Redis@123!
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
redis-list:
    - name: cache
      addr: 127.0.0.1:6379
      password: ""
      db: 0
      useCluster: false
      clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        - host: ""
          port: ""
email:
    to: xxx@qq.com
    from: xxx@163.com
    host: smtp.163.com
    secret: xxx
    nickname: test
    port: 465
    is-ssl: true
system:
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8886
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
    use-strict-auth: false
    node-type: 2
    node-code: 8-20240928232019043-fcb93e735a03
    auth-code: 8-202409
    sl-endpoint: ws://localhost:8888/api/nod/connect
    serve-ip: http://localhost:8080
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
autocode:
    web: web/src
    root: D:\project\ygpt
    server: server
    module: ygpt/server
    ai-path: ""
mysql:
    prefix: ""
    port: "13301"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: cloud
    username: root
    password: MySQL@123!
    path: 10.10.1.200
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
local:
    path: uploads/file
    store-path: uploads/file
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img-path: ""
    access-key: ""
    secret-key: ""
    use-https: false
    use-cdn-domains: false
aliyun-oss:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    bucket-url: yourBucketUrl
    base-path: yourBasePath
hua-wei-obs:
    path: you-path
    bucket: you-bucket
    endpoint: you-endpoint
    access-key: you-access-key
    secret-key: you-secret-key
tencent-cos:
    bucket: xxxxx-10005608
    region: ap-shanghai
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: ygpt/server
aws-s3:
    bucket: xxxxx-10005608
    region: ap-shanghai
    endpoint: ""
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: ygpt/server
    s3-force-path-style: false
    disable-ssl: false
cloudflare-r2:
    bucket: xxxx0bucket
    base-url: https://gin.vue.admin.com
    path: uploads
    account-id: xxx_account_id
    access-key-id: xxx_key_id
    secret-access-key: xxx_secret_key
excel:
    dir: ./hardware/excel/
disk-list:
    - mount-point: /
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
minio:
    EndPoint: 10.10.1.200:19000
    AccessKey: sl-minio
    SecretKey: sl-minio
    BucketName: slpt
    UseSSL: 0
cloudpods:
    authUrl: https://10.10.100.221:30357/v3
    jumpUrl: https://10.10.100.221
    timeout: 60
    debug: false
    insecure: true
    uname: sysadmin
    passwd: VzH8EP9Ny3nu2G2R
    domainName: Default
    tenantName: system
    tanantDomain: Default
    region: region0
    endpointType: publicURL
sl-minio:
    EndPoint: http://10.10.1.200:19000
    AccessKey: sl-minio
    SecretKey: sl-minio
    BucketName: slpt
    UseSSL: 0
sms:
    access-key: AKLTYjExYjAxMTI0NDQ0NGI2MmExZDk0NDQzOTgxODUyYjI
    secret-key: TXpVMlpqWXhaV1ExWXpVM05EaGhOR0l6WkdGbU5XSm1ZV015TlRObVl6SQ==
    sms-account: 7d60ede3
    template-id: ST_7d608a96
    template-sub-id: ""
    template-auth-fail-id: ""
    template-auth-success-id: ""
    template-regis-success-id: ""
    template-alert-id: ST_839283a8
    sms-sign: 浮点运算
    tag: tag
