name: Issue Open Check

on:
  issues:
    types: [opened, reopened]

jobs:
  issue-open-add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v2
        if: ${{ !github.event.comment.pull_request.pull_request }}
        with:
          actions: 'add-labels'
          labels: 'state/awaiting processing'

      - name: Remove require reply label
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'remove-labels'
          labels: 'state/awaiting user feedback,stale'

  notify-author-comment:
    runs-on: ubuntu-latest
    steps:
      - name: feishu notify
        uses: zexi/action-issues-notify@v1
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          issue_title: "${{ github.event.issue.user.login }} 提交了 issue: ${{ github.event.issue.title }}"
          issue_body: "${{ tojson(github.event.issue.body) }}"
          issue_link_url: "${{github.event.issue.html_url}}"
