name: Issue Close Check

on:
  issues:
    types: [closed]

jobs:
  issue-closed-remove-labels:
    runs-on: ubuntu-latest
    if: "!contains(github.event.issue.labels.*.name, 'stale')"
    steps:
      - name: Remove statle labels when issue that hasn't stale label is closed
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'remove-labels'
          labels: 'state/awaiting processing,state/awaiting user feedback'
